# src/main/resources/application.properties

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Generar esquema automáticamente (ideal para MVP)
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola web de H2 (podrás entrar a localhost:8080/h2-console para ver tus datos)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console